apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    tier : frontend
    app: nginx
    environment : dev
spec:
  initContainers:
  - name: init-nginx
    image: busybox:1.32
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: "/app"
  containers:
  - name: basic-nginx
    image: ivorlun/basicnginx8000:0.2
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: app
      mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}
